app = "shared-lists"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 8081

  [[services.ports]]
    port = 8081
    handlers = ["tls", "http"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1